In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
os.getcwd()

'C:\\Users\\Admin\\smart_crosswalk\\analysis'

In [5]:
data_path = '../data/handled/data_for_tableau.xlsx'

In [8]:
data = pd.read_excel(data_path)

In [9]:
data

,Unnamed: 0,index,번호,현장명,방향,일시,신호횟수,운영시간,녹색시간,통과보행자,...,연장_횟수,연장_시간,연장_보행자,교통약자_목발,교통약자_휠체어,교통약자_유모차,교통약자_합계,잔여,보도길이,보행속도
0,0,0,1,자운학교앞(5),동,2021-08-01 00:00:00,23,3352,920,9,...,0,0,0,NaN,NaN,NaN,0,0,35,0.000000
1,1,1,2,자운학교앞(5),NaN,2021-08-01 01:00:00,24,3600,960,1,...,0,0,0,NaN,NaN,NaN,0,2,35,0.000000
2,2,2,3,자운학교앞(5),NaN,2021-08-01 02:00:00,24,3600,965,1,...,0,0,0,NaN,NaN,NaN,0,0,35,0.000000
3,3,3,4,자운학교앞(5),NaN,2021-08-01 03:00:00,24,3600,957,0,...,0,0,0,NaN,NaN,NaN,0,0,35,0.000000
4,4,4,5,자운학교앞(5),NaN,2021-08-01 04:00:00,24,3601,959,0,...,0,0,0,NaN,NaN,NaN,0,0,35,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40482,40482,2871,2872,파주병원(4),NaN,2022-09-30 19:00:00,29,3481,824,17,...,1,5,1,0.0,1.0,0.0,1,0,20,1.000000
40483,40483,2872,2873,파주병원(4),NaN,2022-09-30 20:00:00,30,3600,843,17,...,0,0,0,0.0,0.0,1.0,1,0,20,0.930233
40484,40484,2873,2874,파주병원(4),NaN,2022-09-30 21:00:00,30,3600,848,14,...,2,6,2,2.0,1.0,0.0,3,0,20,1.230769
40485,40485,2874,2875,파주병원(4),NaN,2022-09-30 22:00:00,30,3599,853,13,...,2,12,2,0.0,1.0,0.0,1,0,20,0.945946
40486,40486,2875,2876,파주병원(4),NaN,2022-09-30 23:00:00,31,3720,860,5,...,0,0,0,0.0,0.0,0.0,0,0,20,0.816327